### ISSUE TITLE
Problemas docker 

### ISSUE THREAD

**Issue by AlbaMarin8** [jorditorresBCN/dlaimet#1]
Hola Jordi, 
Soc l'Alba, estudiant d'Audiovisuals de la UPC de terrasa, tinc aquest problema a l'hora d'obtenir el docker.
![docker](https://user-images.githubusercontent.com/32396655/31025956-d85aaa22-a544-11e7-8e5c-4ce5b46ab7c1.jpg)
Moltes Gracies

**Comment by xiscosc** [comment]
Hola, les comandes de docker les has de fer al terminal de docker (Docker CLI). És el terminal que tens obert amb la balena.

Hem actualitzat el lab per fer-ho més fàcil (http://jorditorres.org/getting-started-dlai-course-labs/).

**Comment by xiscosc** [comment]
Si tens algun altre dubte, pots tornar a obrir un issue.
