### ISSUE TITLE
Problemes amb docker windows 10 Home

### ISSUE THREAD

**Issue by irenenus** [jorditorresBCN/dlaimet#2]
Hola Jordi, sóc estudiant de la UPC i tinc un problema amb descarregar-me el Docker, m'he descarregat la versió del windows 10 PRO i em dona un problema: Unable to stop: Se detuvo el comando en ejecución porque la variable de preferencia "ErrorActionPreference" o un parámetro común se han establecido en Stop: No se cargó el módulo 'Hyper-V' especificado porque no se encontró ningún archivo de módulo válido en ningún directorio de módulo.
en <ScriptBlock>, <sin archivo>: línea 79

I en la versió dels altres windows em diu 
![imatgedocker](https://user-images.githubusercontent.com/32396660/31025955-d76910e0-a544-11e7-890c-c3a323bbe935.png)

Moltes gràcies.

**Comment by xiscosc** [comment]
Hola! Primer de tot et recomano desinstalar tots els Dockers que tinguis (normal i toolbox). 
Si tens Windows 10 Home et toca instalar Docker Toolbox i després obrir el Docker Quickstart (Un terminal per fer totes les operacions de docker a Windows). La captura que adjuntes és del Kitematic que no fa falta per aquest lab.

Si tens windows 10 pro, instala docker normal i utilitza el powershell de windows. Si et dona error de Hyper-V, l'has d'habilitar https://docs.microsoft.com/es-es/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

Hem actualitzat el lab per fer-ho més fàcil, fes-hi un cop d'ull (http://jorditorres.org/getting-started-dlai-course-labs/).

**Comment by xiscosc** [comment]
Si tens algun altre dubte, pots tornar a obrir un issue o reobrir aquest si tens més problemes.
